kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rclone-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
  volumeMode: Filesystem
